docs/overview.md, packages/core/src/printer/preparePrintItems.ts, packages/core/src/printer/printWriteItems.ts, packages/core/wasm/src/get_js_write_items.rs, packages/core/wasm/src/get_rust_print_items.rs, packages/core/wasm/src/get_write_items.rs, packages/core/wasm/src/js_types.rs, packages/rust-core/README.md, packages/rust-core/src/collections/fast_cell_map.rs, packages/rust-core/src/collections/graph_node.rs, packages/rust-core/src/collections/mod.rs, packages/rust-core/src/condition_resolvers.rs, packages/rust-core/src/conditions.rs, packages/rust-core/src/get_write_items.rs, packages/rust-core/src/parser_helpers.rs, packages/rust-core/src/print.rs, packages/rust-core/src/print_items.rs, packages/rust-core/src/print_write_items.rs, packages/rust-core/src/printer.rs, packages/rust-core/src/write_items.rs, packages/rust-core/src/writer.rs, packages/rust-core/src/writer_tests.rs, packages/rust-core/tests/sample_example_test.rs, packages/rust-dprint-plugin-typescript/src/format_text.rs, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/src/parser_types.rs, packages/rust-dprint-plugin-typescript/tests/test.rs
This is faster and formats checker.ts in ~772ms.
1. A graph was being constructed on top of the parsed vectors. This graph generation was pushed up to the parsing stage so only one data structure needed to be created.
2. Resolved condition values are now only stored in the printer if someone gets a reference to a condition, which can then be used in a condition resolver. This saves a lot of time and needless memory usage.
3. In the implementation, UnsafeCell is used instead of RefCell. This is made "safe" by hiding away the use of UnsafeCell.
4. Indent "write items" are now stored with a count value. Previously it was pushing a single indent IR the number of times an indent was necessary.
5. This goes back to having the concept of "Signals" in the parsing, which I am very happy about.
6. …
=> Replace vector parsing with graph

packages/rust-dprint-plugin-typescript/Cargo.toml, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/tests/specs/types/TypePredicate/TypePredicate_All.txt
Waiting on https://github.com/swc-project/swc/pull/667 and a release.
Closes #104
=> Support "asserts" keyword without "is"

packages/rust-dprint-plugin-typescript/Cargo.toml, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/src/parser_types.rs, packages/rust-dprint-plugin-typescript/src/tokens.rs, packages/rust-dprint-plugin-typescript/tests/specs/patterns/ArrayPattern/ArrayPattern_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/patterns/ObjectPattern/ObjectPattern_All.txt
Waiting on a fix in swc for: https://github.com/swc-project/swc/issues/709#issuecomment-596888858
Needed to upgrade everything to `SpanData` in order to support the latest swc, but not a big deal because keeping everything as `SpanData` is probably more efficient.
Closes #143, #141
=> Upgrade swc_ecma_parser to 0.23

website/assets/install.ps1
`Expand-Archive` should be available since PowerShell 5.1: https://docs.microsoft.com/de-de/powershell/module/microsoft.powershell.archive/Expand-Archive?view=powershell-5.1
=> fix: Support unzipping on Windows 8.1

.github/workflows/publish.yml
similar to https://github.com/dprint/dprint-plugin-typescript/pull/259
=> chore: do not run external resource-dependent publishes in forks

crates/dprint/src/cli/paths.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/utils/glob_utils.rs
This moves glob specific functionality out of the `RealEnvironment` and `TestEnvironment` so the logic for globbing that was previously in `RealEnvironment` actually gets tested by the tests.
This is now possible due to dropping the `globwalk` dependency in https://github.com/dprint/dprint/commit/5a3b6c213259fb6e3db9a92c346d28a06f7ce644 (unfortunately that also caused some of these bugs, but overall we will be in a better place going forward)
cc @joscha
=> refactor: move glob matching up to a higher level so it can be properly tested

.github/workflows/ci.yml, .github/workflows/website.yml, crates/dprint/src/cli/patterns.rs, crates/dprint/src/cli/run_cli.rs, crates/dprint/src/utils/glob_utils.rs
This restores the behaviour back to the intended .gitignore behaviour.
> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.
Closes #401.
cc @joscha
=> fix: restore searching all directories when glob pattern does not contain a slash at the beginning or middle

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/cli/paths.rs, crates/dprint/src/cli/patterns.rs, crates/dprint/src/utils/glob/glob.rs, crates/dprint/src/utils/glob/glob_matcher.rs, crates/dprint/src/utils/glob/glob_pattern.rs, crates/dprint/src/utils/glob/glob_utils.rs, crates/dprint/src/utils/glob/mod.rs
Closes #417.
cc @joscha - You may wish to try out this PR. I'll do a release tomorrow.
On building, you may have to run:
```bash
cargo build --manifest-path=crates/test-plugin/Cargo.toml --release --target=wasm32-unknown-unknown
cargo build --manifest-path=crates/test-process-plugin/Cargo.toml --release
cargo build --locked --all-features ---release
```
=> Switch to using ignore crate

crates/dprint/src/cli/commands/editor.rs, crates/dprint/src/cli/commands/formatting.rs, crates/dprint/src/cli/commands/general.rs, crates/dprint/src/cli/configuration/resolve_config.rs, crates/dprint/src/cli/paths.rs, crates/dprint/src/cli/patterns.rs, crates/dprint/src/configuration/deserialize_config.rs, crates/dprint/src/configuration/get_global_config.rs, crates/dprint/src/configuration/get_plugin_config_map.rs, crates/dprint/src/configuration/types.rs, crates/dprint/src/plugins/implementations/process/plugin.rs, crates/dprint/src/plugins/implementations/wasm/plugin.rs, crates/dprint/src/plugins/plugin.rs, crates/dprint/src/plugins/pool.rs, crates/dprint/src/utils/glob/glob_matcher.rs
This implements https://github.com/dprint/dprint/issues/365#issuecomment-913279108 where people can provide an `"associations"` key to a plugin config to get it to grab certain files that are matched by the includes/excludes patterns and have that plugin format them.
Todo:
Closes #365
=> feat: add plugin pattern associations

crates/core/src/configuration.rs, crates/core/src/formatting/writer.rs, crates/core/tests/sample_example_test.rs
This makes minor improvements by fixing clippy errors that occur when
linting the tests in crates/core.
=> Fix linter errors for tests in core

Cargo.lock, crates/cli-core/Cargo.toml, crates/cli-core/src/url_utils.rs, crates/dprint/Cargo.toml, crates/dprint/src/commands/config.rs, crates/dprint/src/configuration/get_init_config_file_text.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/environment/test_environment_builder.rs, crates/dprint/src/plugins/cache.rs, crates/dprint/src/plugins/repo/read_info_file.rs, crates/dprint/src/plugins/repo/read_update_url.rs, crates/dprint/src/utils/cached_downloader.rs, crates/dprint/src/utils/mod.rs, crates/dprint/src/utils/resolve_url_or_file_path.rs, crates/test-plugin/src/lib.rs
Adds support for a more distributed `dprint config add <arg>` command (though it still relies on the plugins.dprint.dev service... will be addressed in the future. I think that should be configurable probably).
This isn't explicitly tied to GitHub... it's just that the plugins.dprint.dev service happens to implement it that way (ex. https://plugins.dprint.dev/malobre/vue/latest.json)
Example:
```bash
dprint config add malobre/vue
```
Closes #455
=> feat: `dprint config add <user-or-org>/<repo>`

crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/plugins/cache.rs, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/plugins/implementations/wasm/setup_wasm_plugin.rs
Does this for both Wasm and process plugins.
```
./cache/plugins/<plugin-name>/<version>-<arch>.cached
./cache/plugins/<plugin-name>/<version>/<arch>/<process-plugin-output>
```
Closes #466
=> fix: include CPU architecture in plugin cache path

Cargo.lock, crates/cli-core/Cargo.toml, crates/cli-core/src/logging/logger.rs, crates/dprint/Cargo.toml, crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/config.rs, crates/dprint/src/commands/editor.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/main.rs, crates/dprint/src/test_helpers.rs, rust-toolchain.toml
Spotted this in the vscode output:
```
[ERROR] Error initializing in v:\dprint-plugin-yapf: Error: Error parsing editor info. Output was: [dprint]
{"schemaVersion":4,"cliVersion":"0.22.2","configSchemaUrl":"https://dprint.dev/schemas/v0.json","plugins":[{"name":"dprint-plugin-typescript","version":"0.62.1","configKey":"typescript","fileExtensions":["ts","tsx","js","jsx","mjs","cjs","mts","cts"],"fileNames":[],"configSchemaUrl":"https://plugins.dprint.dev/schemas/typescript-0.62.1.json","helpUrl":"https://dprint.dev/plugins/typescript"},{"name":"dprint-plugin-jsonc","version":"0.7.2","configKey":"json","fileExtensions":["json"],"fileNames":[],"helpUrl":"https://dprint.dev/plugins/json"},{"name":"dprint-plugin-markdown","version":"0.12.1","configKey":"markdown","fileExtensions":["md","mkd"," …
```
=> fix: do not output logging context name for machine readable output

Cargo.lock, crates/core/Cargo.toml, crates/core/src/configuration.rs, crates/core/src/formatting/print_items.rs, crates/core/src/plugins/process/message_processor.rs, crates/core/src/plugins/wasm/mod.rs, crates/dprint/Cargo.toml, crates/dprint/src/configuration/deserialize_config.rs, crates/dprint/src/configuration/get_global_config.rs, crates/dprint/src/configuration/get_plugin_config_map.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/configuration/types.rs, crates/dprint/src/format.rs, crates/dprint/src/plugins/implementations/wasm/plugin.rs, crates/test-plugin/Cargo.toml, crates/test-plugin/src/lib.rs, crates/test-process-plugin/Cargo.toml, crates/test-process-plugin/src/main.rs, docs/process-plugin-development.md, docs/wasm-plugin-development.md
For dprint-plugin-exec it is important to maintain the order of configuration keys because the order determines which binary it will use to format first.
=> feat(core): maintain order of configuration keys

crates/core/src/formatting/print_items.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/paths.rs, crates/dprint/src/patterns.rs, crates/dprint/src/utils/glob/glob_pattern.rs, crates/dprint/src/utils/glob/glob_utils.rs
Previously, dprint would always format the provided file paths. This led to problems with tools like lint-staged where the excludes patterns weren't taken into account. See #473.
With this change, dprint treats all provided include and exclude CLI args as patterns instead of sometimes treating them as file paths (which had a lot of complexity and wasn't exactly right). The args simply override what is present in the config file (as occurred before, but non-glob file paths weren't ever excluded if they matched an excludes pattern).
Closes #473
FYI @joscha @declanvong (not sure this affects the setup you have… probably doesn’t?)
=> feat: exclude patterns are taken into consideration for all "include" CLI args

.github/workflows/ci.yml, Cargo.lock, crates/core/Cargo.toml, crates/core/src/plugins/process/communication.rs, crates/core/src/plugins/process/communicator.rs, crates/core/src/plugins/process/message_processor.rs, crates/core/src/plugins/process/messages.rs, crates/core/src/plugins/process/stdout_message_writer.rs, crates/core/src/plugins/process/utils.rs, crates/dprint/Cargo.toml, crates/dprint/src/commands/editor/mod.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/format.rs, crates/dprint/src/main.rs, crates/dprint/src/paths.rs, crates/dprint/src/plugins/collection.rs, crates/dprint/src/plugins/implementations/mod.rs, crates/dprint/src/plugins/implementations/process/communicator.rs, crates/dprint/src/plugins/implementations/process/plugin.rs, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/plugins/implementations/wasm/import_object.rs, crates/dprint/src/plugins/implementations/wasm/plugin.rs, crates/dprint/src/plugins/plugin.rs, crates/dprint/src/test_helpers.rs, crates/test-process-plugin/Cargo.toml, docs/process-plugin-development.md
Closes #495, but mainly there's a dprint-plugin-prettier change that will fix that. This also reduces the number of threads used for formatting if there are process plugins and subtracts one for any messaging going on in the cli itself (seems to improve formatting speeds).
=> fix: various improvements to the new process plugin system

crates/core/src/formatting/conditions.rs, crates/core/src/formatting/ir_helpers/gen_separated_values.rs, crates/core/src/formatting/print_items.rs, crates/core/src/formatting/printer.rs, crates/core/src/formatting/writer.rs
When telling if we're at the start of a newline, it should take into account if there's a newline expected next.
This also reduces the size of `WriterInfo`.
=> fix(core): add `WriterInfo.expect_newline_next`

crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs
fixed typo
Resolves https://github.com/dprint/dprint-plugin-roslyn/issues/8
=> fix: mac aarch64

deployment/npm/install.js
The install script will fail if the current path contains spaces.
For example, the path `/Users/my name/dprint-project` will produce the error `/bin/sh: /Users/my: No such file or directory` when executing `/Users/my name/dprint-project/node_modules/dprint/install.sh x.x.x` with `exec`. The correct command should be `"/Users/my name/dprint-project/node_modules/dprint/install.sh" x.x.x`.
=> Fix installing from npm in paths with spaces

crates/dprint/src/commands/formatting.rs, crates/dprint/src/format.rs, crates/test-plugin/src/lib.rs
This improves incremental to only cache a file if the formatting of that file is stable (meaning, it does not change when formatted again).
This will make incremental formatting slightly slower, but I think it's worth it because then nobody will get unstable files in their incremental cache.
Closes #509
=> feat: incremental should ensure stable formatting

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs
This is already done for incremental formatting, but now will also be done with non-incremental formatting.
Closes #422
=> feat: use "stable formatting" by default

website/install.md
`dprint` is now in the scoop main bucket.
Relates to ScoopInstaller/Main#3521
=> docs(website): add scoop installation for Windows

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/main.rs
Related to #552. Using wild here doesn't make sense because the arguments are provided as patterns to a glob pattern matcher. It also caused doing stuff like `dprint output-file-paths "*.ts"` to not work on Windows, so removing.
=> fix: improve globbing on Windows

crates/cli-core/src/checksums.rs, crates/dprint/src/plugins/types.rs
=> fix: plugins that were in a directory with an `@` symbol couldn't be loaded

deployment/npm/install_api.js
I know that Node 12 is EOL, but I'd like to test it for some of my projects for now (plus for benchmarking reasons). But this piece of syntax exists in dprint's postinstall script, so if I install my deps, this will error out (even though I don't actually run dprint; it's just in my devDeps).
=> Make install_api.js work under Node 12

crates/dprint/src/commands/upgrade.rs, website/src/install.md
=> fix: error running `dprint upgrade` when user installed dprint via `cargo install`

crates/dprint/Cargo.toml
As discussed in #591 - use system SSL certificates instead of fixed set from Mozilla.
This should not significantly affect most users (Mozilla certificates should usually be available in trust root).
=> #591 - use system-wide SSL certificates instead of fixed ones

crates/dprint/src/arg_parser.rs
=> fix: use a zero exit code for `-V`

website/src/assets/install.sh
This change adds a check for musl to determine whether to download the glibc or musl version of dprint on x86_64 Linux.
=> fix(install): add support for the musl build in install script

crates/core/src/formatting/ir_helpers/gen_separated_values.rs
For use by https://github.com/dprint/dprint-plugin-typescript/pull/502
> Currently, there is a multi line options struct that contains the options for multiple lines.
> 
> This PR aims to achieve a similar result by introducing a struct for single line options.
=> refactor(core): group single line options into single struct

docs/wasm-plugin-development.md
It:
- de-pins the serde patch version
- Uses the `sync` plugin handler
=> docs: update wasm plugin example

crates/dprint/src/commands/formatting.rs, crates/dprint/src/utils/file_path_utils.rs
=> fix: handle `fmt --stdin` when specifying a leading period on the extension

.cargo/config.toml
=> fix: statically link the c runtime on windows

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/incremental/incremental_file.rs, crates/dprint/src/plugins/cache_manifest.rs, crates/dprint/src/plugins/implementations/wasm/setup_wasm_plugin.rs
Do an "atomic write" for more operations where it writes to a temporary file then renames.
=> fix: handle multiple processes writing to Wasm cache at the same time

Cargo.lock, crates/development/Cargo.toml, crates/development/src/spec_helpers.rs
I'm not sure why it wasn't formatting the panic message. This fixes it by unwrapping.
=> fix(development): show panic message when spec panics

crates/dprint/src/configuration/resolve_config.rs, website/src/config.md
There's not any reason to remove "excludes" from remote config.
=> feat: allow "excludes" patterns in remote config

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/arg_parser.rs, crates/dprint/src/main.rs, crates/dprint/src/run_cli.rs, crates/dprint/src/test_helpers.rs
This should add support for generating [tab completion](https://en.wikipedia.org/wiki/Command-line_completion) scripts in run-time using `clap_complete`.
---
It could be done in compile-time, but first we need to isolate the `create_cli_parser` function in a separate file so we can `include!()` it in the `build.rs` file without any complexity.
=> feat: Add shell completions generator

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/format.rs, crates/dprint/src/utils/unsync.rs
This checks CPU usage every 2 seconds after an initial 5 second delay and will scale back formatting.
This will help not overload someone's machine on very large repositories like DefinitelyTyped.
Closes #710
=> feat: monitor and throttle CPU if necessary

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/build.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/plugins/cache.rs, crates/dprint/src/plugins/implementations/wasm/setup_wasm_plugin.rs
After I upgraded to the latest dprint version, I found that the wasm cache was corrupted. It would be best to key on the version of rustc used to build dprint.
=> fix: key wasm plugin cache on rustc version

Cargo.lock, crates/core/Cargo.toml, crates/dprint/Cargo.toml, crates/dprint/src/configuration/deserialize_config.rs
I noticed that the incremental formatting cache was being invalidated for certain configs. This was because jsonc-parser had an unstable deserialization, so I fixed that in https://github.com/dprint/jsonc-parser/pull/39
=> perf: ensure incremental cache doesn't get invalidated via unstable jsonc deserialization

Cargo.lock, crates/core/Cargo.toml, crates/core/src/configuration.rs, crates/dprint/Cargo.toml, crates/dprint/src/configuration/get_global_config.rs
Note: In order for this to work it requires dprint 0.43.0 and for the newline kind configuration to be set at the top level.
The reason the bug occurs is because the plugins get compiled to wasm and so they have no concept of operating system at that point. The fix is to resolve this in the CLI and then passed the resolved global config to the plugins. This also means I will be removing the "system" config from the wasm plugins gradually in the future.
All that said, I highly recommend that Windows devs just use LF newlines. I work on Windows and that's what I do and it's absolutely fine. It leads to less complexity. Just make sure your git config is to check-out newlines "as-is" instead of having it mess with stuff by converting newlines.
Related …
=> fix: resolve 'system' newline global config in CLI

crates/dprint/src/commands/general.rs, crates/dprint/src/configuration/resolve_config.rs
Closes https://github.com/dprint/dprint/issues/795
=> fix: cli include args should not override negated includes in config

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/config.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/paths.rs, crates/dprint/src/patterns.rs, crates/dprint/src/resolution.rs, crates/dprint/src/utils/glob/glob.rs, crates/dprint/src/utils/glob/glob_matcher.rs, crates/dprint/src/utils/glob/glob_pattern.rs, crates/dprint/src/utils/glob/glob_utils.rs, website/src/cli.md
The current behaviour of how the CLI file patterns just override the config is very confusing and doesn't work well.
This change does the following:
1. Paths provided to the CLI are now an intersection with the config includes patterns.
- In other words, this only matches file patterns provided as CLI args that also match the config.
2. Paths provided as `--excludes` are now a union with the config excludes patterns.
- In other words, this excludes patterns in addition to what's excluded in the config.
3. Added a new `--includes-override` flag for overriding the value in the config. This is the previous behaviour of providing includes on the CLI.
4. Added a new `--excludes-override` flag for overriding the "excludes" value in the config. This is the previous behaviour of `--excludes`. …
=> feat: change CLI file patterns to be intersection with the config and excludes to be a union

website/playground/src/plugins/getPluginDefaultConfig.ts, website/src/scripts/plugin-config-table-replacer.js
The generated default config in the [playground](https://dprint.dev/playground/#code/Q/plugin/typescript) is slightly inconsistent:
* Some properties are missing:
* `module.sortImportDeclarations`
* `module.sortExportDeclarations`
* `exportDeclaration.sortNamedExports`
* `importDeclaration.sortNamedImports`
* `exportDeclaration.forceSingleLine`
* `importDeclaration.forceSingleLine`
* `exportDeclaration.forceMultiLine`
* `importDeclaration.forceMultiLine`
* Detecting AST specific properties differs between the playground and the website:
* This PR unifies the logic
* We now regard more properties as AST specific by assuming properties of form `a.b` are an AST specific property of `a` if `a` exists.
* This leads to properties like `arguments.preferHanging` being (correctly) regarded as AST …
=> docs: update detection of AST specific config properties

crates/dprint/src/environment/real_environment.rs, crates/dprint/src/utils/url.rs
I actually did a flamegraph on Mac. I didn't notice it was slow because I use Windows, which was way faster at this.
Before:
```
% time dprint check --incremental=false ./data/package-template.json
0.10s user 0.02s system 65% cpu 0.173 total
```
After:
```
% time ../dprint/target/release/dprint check --incremental=false ./data/package-template.json
0.01s user 0.01s system 67% cpu 0.023 total
```
=> perf: lazily create ureq agents

Cargo.lock, crates/core/src/configuration.rs, crates/dprint/Cargo.toml, crates/dprint/src/configuration/get_global_config.rs, crates/dprint/src/configuration/get_plugin_config_map.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/test_helpers.rs, crates/test-process-plugin/src/main.rs
=> fix: dprint 0.46 release for `cargo install` without `--locked` flag

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/test_helpers.rs, deployment/npm/build.ts
A native build isn't possible at the moment, so I'm updating the npm build to use the x64 build.
Closes https://github.com/dprint/dprint/issues/886
=> fix(npm): use x64 build for aarch64-pc-windows-msvc

README.md, website/src/plugins/markup_fmt.md
Since v0.11.0, markup_fmt supports Angular. This PR updates documentation pages.
---
Off topic: I made some logos for dprint in #893 . Can you check them? If you don't like them, I will close that issue.
=> docs: support Angular

website/src/assets/schemas/v0.json
This fixes part of Issue https://github.com/dprint/dprint-vscode/issues/94 . (Or so I assume. I haven't tested that.) The other part of that issue will be fixed by PR https://github.com/dprint/dprint-vscode/pull/95 when that is merged and deployed.
This changes https://dprint.dev/schemas/v0.json , which the dprint vscode plugin uses in its calculation of the json schema.
=> fix: add `allowTrailingCommas: true` to dprint.json and dprint.jsonc schemas

crates/core/src/plugins/wasm/mod.rs
Currently `Configuration` was hard-coded, which can confuse people who is developing plugins. In my plugins, configuration type isn't called `Configuration`, so I have to add some code like this:
- markup_fmt: https://github.com/g-plane/markup_fmt/blob/2f83a808571d9c6ed55b5d00ccc93c923ce9d1e5/dprint_plugin/src/lib.rs#L18
- Malva: https://github.com/g-plane/malva/blob/b4d2471a99697a51710264148a54b025c5944fa9/dprint_plugin/src/lib.rs#L15
- Pretty YAML: https://github.com/g-plane/pretty_yaml/blob/118bad7b3d677e38d68f80f36660b4cb41cbe2aa/dprint_plugin/src/lib.rs#L15
After this PR, I can remove all the code above and update the `generate_plugin_code!` call like this:
```diff
- generate_plugin_code!(PrettyYamlPluginHandler, PrettyYamlPluginHandler);
+ …
```
=> feat: allow to specify custom config type name

crates/dprint/src/configuration/get_init_config_file_text.rs
=> fix: init message should handle when dprint version has newer wasm plugin support

website/playground/package-lock.json, website/playground/package.json, website/playground/src/Playground.tsx
Every time I go to make a playground link for a bug report, I get confused and then realize that I copied my own config into the editor with comments, which then silently fails.
This PR instead uses `JSON5.parse`. Technically, dprint supports JSONC (so, maybe `jsonc-parser` would be better?), but I honestly don't know that the feature sets are any different and JSON5 was already a transitive dep with an API more similar to `JSON.parse`.
=> Parse playground config with JSON5 instead of JSON

crates/core/src/plugins/wasm/mod.rs
The error was introduced in https://github.com/dprint/dprint/commit/9c6686af5e5bd91bdddb0c807537d4325edf5e51
```rust
error: macros that expand to items must be delimited with braces or followed by a semicolon
--> C:\Users\Balthild\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dprint-core-0.67.1\src\plugins\wasm\mod.rs:65:28
|
63 |   macro_rules! generate_plugin_code {
|   --------------------------------- in this expansion of `generate_plugin_code!`
64 |     ($wasm_plugin_struct:ident, $wasm_plugin_creation:expr) => {
65 |       generate_plugin_code!($wasm_plugin_struct, $wasm_plugin_creation, Configuration)
|                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
::: src\wasm_plugin.rs:65:1
|
65 | generate_plugin_code!(TypeScriptPluginHandler, …
```
=> fix: macro syntax error

Cargo.lock, crates/dprint/Cargo.toml
https://github.com/dprint/jsonc-parser/pull/49
=> fix: do not panic modifying dprint.json with crlf newlines

deployment/npm/install_api.js
This will save a bit of space.
=> fix(npm): hardlink main package executable to specific executable instead of copying

crates/dprint/src/commands/lsp/mod.rs
I've recently had this behaviour with vscode where it takes forever to do a formatting request when also running a cargo build. I logged out this and it seems dprint is responding very quickly < 100ms, so maybe a vscode or dprint-vscode issue.
=> fix(lsp): debug log duration of format request

Cargo.lock, crates/core/src/communication/reader_writer.rs, crates/dprint/Cargo.toml, crates/dprint/src/commands/general.rs, crates/dprint/src/plugins/implementations/wasm/instance/v4.rs, crates/dprint/src/utils/extract_zip.rs, crates/dprint/src/utils/url.rs
Error instead of panic when a plugin or dprint sends a format request or response that the receiver doesn't have memory to allocate.
=> fix: error in more cases when cannot pre-allocate

crates/core/Cargo.toml
I was reading about [Wasm plugins](https://github.com/dprint/dprint/blob/main/docs/wasm-plugin-development.md) and wondered why I couldn't find the `plugins` module on https://docs.rs/dprint-core. I think it's just because the feature isn't enabled by default.
=> docs: enable all features on docs.rs

website/src/setup.md
That header looks ugly. Whatever.
=> chore: fix version specified in unsafely ignoring certs docs

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, .github/workflows/website.yml, Cargo.lock, crates/core/src/formatting/collections/vec_u32_map.rs, crates/core/src/plugins/process/message_processor.rs, crates/dprint/Cargo.toml, crates/dprint/src/paths.rs, crates/dprint/src/utils/lax_single_process_fs_flag.rs, rust-toolchain.toml
There was a security issue in zip 2.2 and so it was yanked. I don't believe dprint is affected by this security issue because it's executing a sub process in the zip file so all bets are off anyway.
Closes https://github.com/dprint/dprint/issues/970
=> fix: bump zip crate to 2.4.1
