dprint/dprint

packages/rust-dprint-plugin-typescript/Cargo.toml, packages/rust-dprint-plugin-typescript/src/parse_to_swc_ast.rs, packages/rust-dprint-plugin-typescript/src/parser_types.rs, packages/rust-dprint-plugin-typescript/src/utils/string_utils.rs, packages/rust-dprint-plugin-typescript/tests/specs/declarations/function/Function_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/expressions/FunctionExpression/FunctionExpression_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/issues/issue058.txt
Fixes #58.
Still need to upgrade to the latest version of swc in order to get the async generator fix, but am waiting on some small jsx fix.
=> Fix panic due to unobserved diagnostic

.travis.yml, packages/core/package.json, packages/dprint-plugin-typescript/package.json, packages/playground/package.json, packages/rust-dprint-plugin-typescript/tests/performance/checker_output.txt
=> Use wasm-pack as an npm dev dependency

packages/core/wasm/Cargo.lock, packages/dprint-plugin-typescript/wasm/Cargo.lock, packages/rust-core/Cargo.toml, packages/rust-dprint-plugin-typescript/Cargo.toml, packages/rust-dprint-plugin-typescript/src/parse_swc_ast.rs, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/tests/specs/expressions/AwaitExpression/AwaitExpression_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/emptyStatement/EmptyStatement_All.txt
Implements #88.
Small issue in swc, so opened https://github.com/swc-project/swc/pull/630 and will wait for a new release.
=> Support top level await

packages/rust-dprint-plugin-typescript/src/comments.rs, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/src/parser_types.rs, packages/rust-dprint-plugin-typescript/src/tokens.rs, packages/rust-dprint-plugin-typescript/tests/specs/comments/InnerComments_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/class/ClassDeclaration_Body.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/class/ClassDeclaration_Body_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/class/ClassDeclaration_Header.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/function/Function_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/interface/InterfaceDeclaration_Body.txt, packages/rust-dprint-plugin-typescript/tests/specs/declarations/module/ModuleDeclaration_Body.txt, packages/rust-dprint-plugin-typescript/tests/specs/expressions/ArrayExpression/ArrayExpression_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/expressions/ArrayExpression/ArrayExpression_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/expressions/ArrowFunctionExpression/ArrowFunctionExpression_UseParentheses_Maintain.txt, packages/rust-dprint-plugin-typescript/tests/specs/expressions/ObjectExpression/ObjectExpression_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/general/Arguments_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/blockStatement/BlockStatement_All.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/blockStatement/BlockStatement_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/ifStatement/IfStatement_Comments.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/ifStatement/IfStatement_HeaderComment.txt, packages/rust-dprint-plugin-typescript/tests/specs/statements/switchStatement/switchCase/SwitchCase_All.txt
Closes #96
This is a bit of a mess, as per usual, but should be a good enough starting point for now.
=> Fix comments inside empty braces, brackets, and parens

packages/core/wasm/Cargo.lock, packages/dprint-plugin-typescript/wasm/Cargo.lock, packages/playground/wasm/Cargo.lock, packages/rust-core/Cargo.toml, packages/rust-core/src/condition_resolvers.rs, packages/rust-core/src/conditions.rs, packages/rust-dprint-plugin-typescript/Cargo.toml, packages/rust-dprint-plugin-typescript/src/parser.rs, packages/rust-dprint-plugin-typescript/src/parser_types.rs, packages/rust-dprint-plugin-typescript/src/tokens.rs, packages/rust-dprint-plugin-typescript/tests/specs/issues/issue140.txt, packages/rust-dprint-plugin-typescript/tests/specs/types/TypeAnnotation/TypeAnnotation_All.txt
Closes #144 
Requires https://github.com/swc-project/swc/pull/721 to be merged.
=> Improve comment line after assignment operator

website/assets/install.sh
copy from deno_install
https://github.com/denoland/deno_install/blob/b638c90d11dfd53563326d289c3fbb589de7597c/install.sh#L59-L62
=> suggest the correct path based on the users actual running shell

.github/workflows/ci.yml, README.md, website/install.md
=> docs: update brew install

.github/dependabot.yml
add dependabot support to automate the dependencies (as well as security dependency patches)
=> chore: add dependabot to automate dependencies

crates/dprint/Cargo.toml, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/main.rs
=> Fix Windows platform path generation and matching issues

.github/workflows/ci.yml, .github/workflows/publish.yml, deployment/npm/.npmignore, deployment/npm/LICENSE, deployment/npm/README.md, deployment/npm/bin.js, deployment/npm/info.json, deployment/npm/install.js, deployment/npm/install.ps1, deployment/npm/install.sh, deployment/npm/package.json, deployment/npm/setup.js, website/assets/install.sh
=> Add npm package

crates/dprint/src/cli/run_cli.rs
Resolves https://github.com/dprint/dprint/issues/379. 
Previously, the "check path" flow in the editor service would unconditionally re-glob the working directory. 
This PR makes it so that we glob the working directory once, on service startup, and cache the list of resolved files and file patterns from the config file.
"Check path" will now:
- Reevaluate the config file to see if the includes / excludes has changed. If so, we re-resolve file paths. 
- Otherwise, just check against the cached list. 
- If we can't find the file, it may be a new file, so we re-resolve and try again (only once). 
This resolves the performance issue in the majority case, which is doing a quick format (e.g. on save) on an existing file, in a large codebase.
For reviewing, I recommend enabling GH's "Ignore …
=> editor service: keep resolved project files instead of evaluating each time

crates/dprint/src/commands/editor.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/format.rs, crates/dprint/src/paths.rs, crates/dprint/src/plugins/implementations/common.rs, crates/dprint/src/plugins/pool.rs, crates/dprint/src/plugins/worker/do_batch_format.rs, crates/dprint/src/plugins/worker/local_plugin_work.rs, crates/dprint/src/plugins/worker/local_work.rs, crates/dprint/src/plugins/worker/worker.rs, crates/dprint/src/plugins/worker/worker_registry.rs
This is a super quick pass that I just did in the last couple of hours. I need to write tests for this then do a clean up.
I need to extract out this thread pool logic more to simplify this I think. It's quite complicated.
Todo:
Closes #438
=> feat: ability to format the same file with multiple plugins via associations

Cargo.lock, crates/core/Cargo.toml, crates/core/src/formatting/conditions.rs, crates/core/src/formatting/ir_helpers/gen_separated_values.rs, crates/core/src/formatting/ir_helpers/helpers.rs, crates/core/src/formatting/ir_helpers/mod.rs, crates/core/src/formatting/mod.rs, crates/core/src/formatting/parser_helpers/mod.rs, crates/core/src/formatting/printer.rs, crates/core/tests/sample_example_test.rs, crates/dprint/Cargo.toml, docs/overview.md
=> refactor(core): remove "parse" terminology and replace with "generate"

website/install.md
Hello, I've added a document to website for installation dprint by [asdf-vm](https://asdf-vm.com/), [asdf-dprint](https://github.com/asdf-community/asdf-dprint). 
Thanks.
=> docs: Add installation by asdf-vm

crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs
=> feat: support aarch64 mac process plugins

.github/workflows/ci.yml, .gitignore, crates/dprint/src/commands/general.rs, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/test_helpers.rs, crates/test-plugin/LICENSE, crates/test-process-plugin/LICENSE, deployment/npm/info.json, deployment/npm/install.js, deployment/npm/install.sh, deployment/npm/install_verify_checksum.js, deployment/npm/setup.js
=> feat: add M1 build

README.md, scripts/build-homepage.js, website/index.html, website/plugins/exec.md, website/templates/documentation.html
=> docs(website): add dprint-plugin-exec

.github/workflows/ci.yml, Cargo.lock, crates/dprint/Cargo.toml
For #483. Maybe this will fix that?
=> chore(ci): use older version of ubuntu for CI

website/ci.md
=> docs(website): add dprint-ci

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/editor/mod.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/incremental/mod.rs, crates/dprint/src/paths.rs, crates/dprint/src/patterns.rs, crates/dprint/src/run_cli.rs, crates/dprint/src/test_helpers.rs
=> refactor: upgrade to clap v3

crates/cli-core/src/checksums.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/environment/test_environment_builder.rs, crates/dprint/src/plugins/cache.rs, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/plugins/types.rs
=> feat: improve checksum error messages

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/configuration/get_init_config_file_text.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/incremental/mod.rs, website/cli.md, website/config.md
=> feat: incremental formatting by default

crates/dprint/src/commands/editor/mod.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/utils/mod.rs, crates/dprint/src/utils/update_checker.rs
=> feat: output message in help text if CLI version is out of date

Cargo.lock, crates/core/Cargo.toml, crates/core/src/configuration.rs, crates/dprint/Cargo.toml, crates/dprint/src/configuration/deserialize_config.rs
This requires the plugins to upgrade to dprint_core 0.57
Closes #530
=> feat: support arrays and objects in plugin config

.github/workflows/website.yml, crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/commands/mod.rs, crates/dprint/src/commands/upgrade.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/main.rs, crates/dprint/src/run_cli.rs, crates/dprint/src/test_helpers.rs, crates/dprint/src/utils/update_checker.rs, website/src/cli.md, website/src/install.md
=> feat: `dprint upgrade`

crates/dprint/src/utils/glob/glob_matcher.rs
Adding more logging for #540 because not sure what's going on here.
=> chore: logging for issue 540

.github/workflows/ci.yml, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, crates/dprint/src/test_helpers.rs, deployment/npm/install.js, deployment/npm/setup.js, website/src/assets/install.sh
=> feat: support linux arm64

Cargo.lock, crates/dprint/Cargo.toml, deployment/npm/install.js
=> fix: npm for linux arm64 executable

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/config.rs, crates/dprint/src/run_cli.rs
this allows to disable prompts to confirm that we want to change url of the plugin
=> feat(cli): add --yes to dprint config update

crates/dprint/src/commands/editor/mod.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/format.rs, website/src/setup.md
=> feat: add `DPRINT_MAX_THREADS` env var

deployment/npm/install_api.js
=> fix(npm): retry downloading zip file 3 times if it fails

crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/utils/logging/logger.rs, crates/dprint/src/utils/url.rs
=> fix: use connection pool for downloading and retry downloads 3 times

Cargo.lock, crates/core/Cargo.toml, crates/core/src/formatting/print_items.rs, crates/dprint/Cargo.toml
Uses https://crates.io/crates/unicode-width
=> feat(core): determine width of string according to Unicode Standard Annex #11 rules

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/dprint/Cargo.toml, crates/dprint/src/commands/general.rs, crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/utils/logging/confirm.rs, crates/dprint/src/utils/logging/logger.rs, crates/dprint/src/utils/logging/multi_select.rs, crates/dprint/src/utils/logging/progress_bars.rs, crates/dprint/src/utils/logging/select.rs, crates/dprint/src/utils/terminal.rs
Updates to use [console_static_text](https://crates.io/crates/console_static_text)
=> fix: slight progress bar improvement

.github/workflows/ci.yml, crates/dprint/build.rs, crates/dprint/src/commands/upgrade.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/plugins/implementations/process/setup_process_plugin.rs, deployment/npm/install_api.js
Since i don't know js a lot i could not update [deployment](https://github.com/dprint/dprint/tree/main/deployment)
Now you should just update plugins json files. [for example](https://plugins.dprint.dev/prettier-0.15.0.json)
[I gave you write access to my fork so you can improve the code if you see anything wrong](https://github.com/XDream8/dprint/invitations).
=> feat: musl libc support

deployment/npm/install_api.js, deployment/npm/package.json
=> fix(deployment): support HTTP_PROXY and HTTPS_PROXY in npm package install

deployment/npm/install_api.js, deployment/npm/setup.js
=> fix(npm): aarch64 linux installs were not working

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Forgot. Opened https://github.com/dprint/dprint/issues/623
=> chore(release): actually fix npm release

Cargo.lock, crates/core/Cargo.toml, crates/dprint/Cargo.toml, crates/dprint/src/utils/logging/logger.rs
=> fix: upgrade to ureq 2.6.2

crates/core/src/configuration.rs
Super quick PR to implement `From` on the `RecommendedGlobalConfiguration` struct.
=> feat(core): Implement From<GlobalConfiguration> for RecommendedGlobalConfiguration

.github/workflows/ci.generate.ts, .github/workflows/website.yml, website/deno.json
=> chore: fix playground

crates/dprint/src/plugins/cache_manifest.rs
The caching is not good and could be improved, but for now just bump the version.
Closes #636
=> fix: bust plugin cache

Cargo.lock, crates/dprint/Cargo.toml
=> fix: downgrade crossterm to 0.25

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, crates/dprint/src/environment/real_environment.rs
=> fix: ensure cache directory is created before canonicalizing

website/src/assets/schemas/v0.json, website/src/config.md
=> docs: document `newLineKind` under global configuration

website/_config.ts, website/deno.lock, website/src/style.scss
=> chore(docs): add anchor tags to headers

Cargo.lock, crates/dprint/Cargo.toml
=> fix: pin rkyv version

Cargo.lock, crates/core/src/communication/message.rs, crates/core/src/communication/reader_writer.rs, crates/core/src/plugins/process/communicator.rs, crates/core/src/plugins/process/context.rs, crates/core/src/plugins/process/message_processor.rs, crates/core/src/plugins/process/messages.rs, crates/dprint/src/commands/editor/messages.rs
=> refactor(core): remove some usages of anyhow

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/main.rs, crates/dprint/src/paths.rs, crates/dprint/src/plugins/mod.rs, crates/dprint/src/run_cli.rs, crates/dprint/src/test_helpers.rs, website/src/cli.md
=> feat: fine grained exit codes

deployment/npm/install_api.js
The previous code wouldn't work in Deno.
=> fix(npm): make binary npm package resolution more reliable

deployment/npm/build.ts
I seem to have run into a bug with npm workspaces. Will look into it later and for now do this workaround.
=> ci: fix publish

deployment/npm/bin.js, deployment/npm/build.ts, deployment/npm/install_api.js
=> fix(npm): make it work with yarn berry and readonly file systems

crates/dprint/src/configuration/resolve_config.rs
=> feat: allow includes/excludes when extending non-remote config files

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/website.yml, crates/dprint/src/commands/formatting.rs, crates/dprint/src/commands/general.rs, crates/dprint/src/configuration/resolve_config.rs, crates/dprint/src/paths.rs, crates/dprint/src/patterns.rs, crates/dprint/src/utils/glob/glob.rs, crates/dprint/src/utils/glob/glob_matcher.rs, crates/dprint/src/utils/glob/glob_pattern.rs, dprint.json, website/src/config.md, website/src/plugins/dockerfile.md, website/src/plugins/json.md, website/src/plugins/markdown.md, website/src/plugins/toml.md, website/src/plugins/typescript.md
=> feat: make using "includes" not the default

deployment/npm/build.ts
=> fix(npm): remove bin.js from platform specific package.json files

crates/dprint/src/configuration/resolve_config.rs
=> fix: properly handle "excludes" in extended config

crates/dprint/src/commands/formatting.rs, crates/dprint/src/resolution.rs, crates/dprint/src/utils/path_source.rs
=> fix: do not error for `--config` in sub dir in some cases (regression)

crates/dprint/src/commands/general.rs, crates/dprint/src/configuration/get_init_config_file_text.rs
=> fix: `dprint init` should not have includes pattern anymore

crates/core/src/plugins/process/communicator.rs, crates/core/src/plugins/process/message_processor.rs, dprint.json
=> fix: improve error message when process plugin is too old

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
=> chore: re-enable integration test

crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/plugins/implementations/wasm/setup_wasm_plugin.rs
=> fix: key Wasm cache on CPU features

crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/utils/glob/glob.rs
=> fix: log and ignore PermissionDenied errors when globbing

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, website/src/cli.md
Closes https://github.com/dprint/dprint/issues/753
=> feat(check): --list-different flag

.cargo/config.toml, .github/workflows/ci.generate.ts, .github/workflows/ci.yml
=> chore: try fix musl release build

crates/development/src/config_helpers.rs, crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/resolution.rs, rust-toolchain.toml, website/src/cli.md
=> feat: --allow-no-files

website/playground/src/plugins/getPluginUrls.ts, website/playground/src/utils/UrlSharer.ts, website/src/_includes/layouts/documentation.njk, website/src/index.njk, website/src/plugins.md, website/src/plugins/biome.md, website/src/plugins/dockerfile.md, website/src/plugins/json.md, website/src/plugins/markdown.md, website/src/plugins/ruff.md, website/src/plugins/ruff/config.md, website/src/plugins/toml.md, website/src/plugins/yapf.md, website/src/scripts/plugin-url-replacer.js
The code here is terrible, but I'm too lazy to upgrade it atm.
=> docs: add Ruff plugin to documentation

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, crates/dprint/src/paths.rs, crates/dprint/src/resolution.rs
=> fix: smarter 'no files found' error when providing cli args and has nested configs

Cargo.lock, crates/dprint/Cargo.toml, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/plugins/cache.rs, crates/dprint/src/plugins/implementations/wasm/setup_wasm_plugin.rs
=> fix: upgrade wasmer to 4.2.5

crates/development/Cargo.toml
Found by the [Rust Digger](https://rust-digger.code-maven.com/)
=> chore(development): add repository to Cargo.toml

crates/dprint/src/configuration/resolve_config.rs, website/src/config.md
=> feat: add `${configDir}` and `${originConfigDir}` configuration template variables

dprint.json, website/playground/public/index.html, website/playground/src/external/react-splitpane.css, website/playground/src/index.css, website/src/_includes/layouts/documentation.njk, website/src/_includes/layouts/full_page.njk, website/src/index.njk
=> chore: use malva and markup_fmt plugins internally

dprint.json
=> chore: upgrade markup_fmt

website/src/_includes/layouts/documentation.njk, website/src/index.njk, website/src/plugins/malva.md, website/src/plugins/malva/config.md, website/src/plugins/markup_fmt.md, website/src/plugins/markup_fmt/config.md, website/src/plugins/yaml.md, website/src/plugins/yaml/config.md, website/src/scripts/plugin-url-replacer.js
Close #492 
Close #536 
Close #736 
Close #805 
We can drop Prettier now.
=> chore(website): add Malva, markup_fmt and YAML to list

crates/dprint/src/arg_parser.rs, website/src/cli.md
fixes https://github.com/dprint/dprint/issues/879
=> fix(staged): do not error when `--staged` can't find any files

website/src/_includes/layouts/documentation.njk, website/src/index.njk, website/src/plugins/pretty_yaml.md, website/src/plugins/pretty_yaml/config.md, website/src/plugins/yaml/config.md
=> docs: update YAML to "Pretty YAML"

website/src/install.md
=> docs: add more installation instructions

website/playground/config-overrides.js, website/playground/src/components/CodeEditor.tsx, website/playground/src/plugins/getPluginUrls.ts, website/playground/src/utils/UrlSharer.ts, website/src/plugins/malva.md, website/src/plugins/markup_fmt.md, website/src/plugins/pretty_yaml.md
=> chore(website): add third-party plugins to playground

docs/wasm-plugin-development.md
There seems to be some API updates in the latest version.
=> docs: make wasm example work

website/src/plugins.md
Fixes broken link on plugins page.
=> docs: fix markup_fmt link

README.md, website/playground/src/plugins/getPluginUrls.ts, website/src/_includes/layouts/documentation.njk, website/src/index.njk, website/src/plugins.md, website/src/plugins/pretty_graphql.md, website/src/plugins/pretty_graphql/config.md, website/src/scripts/plugin-url-replacer.js
This PR adds Pretty GraphQL to website.
Close #559
=> feat(website): add pretty_graphql

website/playground/src/utils/UrlSharer.ts
This PR fixes broken URL with Pretty GraphQL in playground.
=> fix(website): fix "pretty_graphql" in playground URL

website/src/scripts/plugin-config-table-replacer.js
Currently "Very Experimental" will be added to `preferSingleLine` in all plugins. This PR limits this to official plugins only.
=> fix(website): add "very experimental" to official plugins only

Cargo.lock, Cargo.toml, crates/dprint/Cargo.toml, crates/dprint/src/commands/config.rs, crates/dprint/src/configuration/deserialize_config.rs, crates/dprint/src/configuration/manipulation.rs, crates/dprint/src/configuration/resolve_config.rs
=> fix: improve automated config file editing and respect trailing commas

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Might help https://github.com/dprint/dprint/issues/956 ... it's also just better to do this in general (see https://github.com/dprint/dprint-plugin-prettier/issues/89)
=> chore: build linux aarch64 on buildjet

crates/dprint/src/environment/environment.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/environment/test_environment.rs, crates/dprint/src/utils/resolve_url_or_file_path.rs
=> feat: support resolving paths to home directory

crates/dprint/src/utils/resolve_url_or_file_path.rs
Tests for https://github.com/dprint/dprint/pull/937
=> chore: tests for resolving home directory

crates/dprint/src/arg_parser.rs, crates/dprint/src/environment/real_environment.rs, crates/dprint/src/test_helpers.rs, crates/dprint/src/utils/url.rs, website/src/setup.md
See https://github.com/dprint/dprint/compare/feat_add_dprint_ignore_certs?expand=1#diff-d8336b1ad5b55f5a40b1e5d81010b9fb74bf349a014140bec0db25a007481e66 for usage.
Closes #955
=> feat: add ability to ignore all or some TLS certificates

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
=> chore: update CI runners to ubuntu-22.04

Cargo.lock, crates/dprint/Cargo.toml
=> fix: upgrade crate url to 2.5.4

crates/dprint/src/arg_parser.rs, crates/dprint/src/commands/formatting.rs, website/src/cli.md
Follow-up to https://github.com/dprint/dprint/pull/982
=> feat: `--config-discovery=ignore-descendants`

README.md, website/src/plugins/malva.md, website/src/plugins/markup_fmt.md, website/src/plugins/pretty_yaml.md
=> docs: change about markup_fmt

crates/dprint/src/utils/url.rs
=> fix: ignore empty proxy env

website/src/install.md
=> docs: add python instructions
